<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Ringcaptcha Verification Success!!</title>
    <link rel="stylesheet" type="text/css" href="assets/view.css" media="all">
    <script type="text/javascript" src="assets/view.js"></script>
</head>
<body id="main_body" >
    <img id="top" src="assets/top.png" alt="">
    <div id="form_container">
        <h1><a>Ringcaptcha Verification Success!!</a></h1>
        <form id="form_240153" class="appnitro"  method="post" action="">
            <div class="form_description">
                <h2>Ringcaptcha Verification Success!!</h2>
            </div>
            <ul>
                <li class="section_break">
                    <label>Transaction ID: <strong><?php echo $transactionID ?></strong></label>
                </li>
                <li class="section_break">
                    <label>Phone Number: <strong><?php echo $phoneNumber ?></strong></label>
                </li>
                <li class="section_break">
                    <label>Is Geolocated: <strong><?php echo ($geolocation) ? 'TRUE' : 'FALSE' ?></strong></label>
                </li>
                <ul>
                <li class="section_break">
                    <label>Try Again: <strong><a href="<?php echo $formPage ?>"><?php echo $formPage ?></a></strong></label>
                </li>
            </ul>
            </ul>
        </form>
        <div id="footer">
            Generated by <a href="http://www.phpform.org">pForm</a>
        </div>
    </div>
    <img id="bottom" src="assets/bottom.png" alt="">
</body>
</html>
